### ISSUE TITLE
panos_dag_tags unexpected failure.

### ISSUE THREAD

**Issue by scott-abt** [PaloAltoNetworks/ansible-pan#24]
When I try to use the panos_dag_tags task to create ip -> tag mapping, I get an unexpected error. Here's my yaml snip:
`  - name: update tag
      panos_dag_tags:
        ip_address: "{{ inventory_hostname }}"
        username: "{{ pan_user }}"
        password: "{{ pan_pass }}"
        tag_names: "{{ new_address_tag }}"
        ip_to_register: "{{ new_address_cidr }}"
        operation: "add"
      tags: "{{ new_address_tag }}"
`
And here's the python error from -vvv:
`TASK [update tag] ************************************************************************************************************************************************************************************
task path: /home/scott/Scripts/Playbooks/paloalto/tag_address.yml:47
The full traceback is:
Traceback (most recent call last):
  File "/home/scott/.local/lib/python3.5/site-packages/ansible/executor/task_executor.py", line 125, in run
    res = self._execute()
  File "/home/scott/.local/lib/python3.5/site-packages/ansible/executor/task_executor.py", line 522, in _execute
    result = self._handler.run(task_vars=variables)
  File "/home/scott/.local/lib/python3.5/site-packages/ansible/plugins/action/normal.py", line 45, in run
    results = merge_hash(results, self._execute_module(tmp=tmp, task_vars=task_vars, wrap_async=wrap_async))
  File "/home/scott/.local/lib/python3.5/site-packages/ansible/plugins/action/__init__.py", line 632, in _execute_module
    (module_style, shebang, module_data, module_path) = self._configure_module(module_name=module_name, module_args=module_args, task_vars=task_vars)
  File "/home/scott/.local/lib/python3.5/site-packages/ansible/plugins/action/__init__.py", line 157, in _configure_module
    task_vars=task_vars, module_compression=self._play_context.module_compression)
  File "/home/scott/.local/lib/python3.5/site-packages/ansible/executor/module_common.py", line 796, in modify_module
    (b_module_data, module_style, shebang) = _find_module_utils(module_name, b_module_data, module_path, module_args, task_vars, module_compression)
  File "/home/scott/.local/lib/python3.5/site-packages/ansible/executor/module_common.py", line 678, in _find_module_utils
    recursive_finder(module_name, b_module_data, py_module_names, py_module_cache, zf)
  File "/home/scott/.local/lib/python3.5/site-packages/ansible/executor/module_common.py", line 462, in recursive_finder
    tree = ast.parse(data)
  File "/usr/lib/python3.5/ast.py", line 35, in parse
    return compile(source, filename, mode, PyCF_ONLY_AST)
  File "<unknown>", line 89
    except Exception, e:
                    ^
SyntaxError: invalid syntax

fatal: [10.7.2.7]: FAILED! => {
    "failed": true,
    "msg": "Unexpected failure during module execution.",
    "stdout": ""
}
    to retry, use: --limit @/home/scott/Scripts/Playbooks/paloalto/tag_address.retry

PLAY RECAP *******************************************************************************************************************************************************************************************10.7.2.7                   : ok=5    changed=0    unreachable=0    failed=1   
`

**Comment by scott-abt** [comment]
I think maybe this has to do with having python 3 installed alongside python 2. I'm going to create a CentOS VM clean and only install Python 2 and see how that goes.

**Comment by scott-abt** [comment]
That was the problem. For whatever reason, ansible was trying to use Python3 for this module. Running on a machine which only has Python 2 allows the module to run. Now I just need to figure out why it's causing Panorama to become unresponsive. :-/
