### ISSUE TITLE
panos_op.py show system infow does not work with version 8.1.4

### ISSUE THREAD

**Issue by martino76** [PaloAltoNetworks/ansible-pan#264]
This is my playbook which works fine against PA version 8.1.8

```
---
- name: show version
  hosts: PA

 
  tasks:
    - name: import role network engine
      import_role:
         name: PaloAltoNetworks.paloaltonetworks


    - name: show system
      panos_op:
       ip_address: "{{ ansible_host }}"
       username: "{{ ansible_user }}"
       password: "{{ ansible_password }}"
       cmd: 'show system info'
      connection: local
      register: show_system

    - name: set_fact
      set_fact:
       show: "{{ (show_system.stdout | from_json) | regex_replace('sw-version', 'sw_version') | regex_replace('ip-address', 'ip_address') }}"

    - name:  debug
      debug: var=show.response.result.system

```

however run against 8.1.4 gives following error

```
EXEC /bin/sh -c 'rm -f -r /home/administrator/.ansible/tmp/ansible-tmp-1553168287.12-1444346340367/ > /dev/null 2>&1 && sleep 0'
The full traceback is:
Traceback (most recent call last):
  File "/home/administrator/.ansible/tmp/ansible-tmp-1553168287.12-1444346340367/AnsiballZ_panos_op.py", line 113, in <module>
    _ansiballz_main()
  File "/home/administrator/.ansible/tmp/ansible-tmp-1553168287.12-1444346340367/AnsiballZ_panos_op.py", line 105, in _ansiballz_main
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
  File "/home/administrator/.ansible/tmp/ansible-tmp-1553168287.12-1444346340367/AnsiballZ_panos_op.py", line 48, in invoke_module
    imp.load_module('__main__', mod, module, MOD_DESC)
  File "/tmp/ansible_panos_op_payload_86fVYv/__main__.py", line 159, in <module>
  File "/tmp/ansible_panos_op_payload_86fVYv/__main__.py", line 130, in main
  File "/home/administrator/.local/lib/python2.7/site-packages/pandevice/base.py", line 3277, in create_from_device
    system_info = device.refresh_system_info()
  File "/home/administrator/.local/lib/python2.7/site-packages/pandevice/base.py", line 3685, in refresh_system_info
    system_info = self.show_system_info()
  File "/home/administrator/.local/lib/python2.7/site-packages/pandevice/base.py", line 3642, in show_system_info
    root = self.xapi.op(cmd="show system info", cmd_xml=True)
  File "/home/administrator/.local/lib/python2.7/site-packages/pandevice/base.py", line 3403, in method
    raise the_exception
pandevice.errors.PanURLError: URLError: code: 403 reason: Forbidden
fatal: [IEDP02-Arachas-PAv01]: FAILED! => {
    "changed": false, 
    "module_stderr": "Traceback (most recent call last):\n  File \"/home/administrator/.ansible/tmp/ansible-tmp-1553168287.12-1444346340367/AnsiballZ_panos_op.py\", line 113, in <module>\n    _ansiballz_main()\n  File \"/home/administrator/.ansible/tmp/ansible-tmp-1553168287.12-1444346340367/AnsiballZ_panos_op.py\", line 105, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/home/administrator/.ansible/tmp/ansible-tmp-1553168287.12-1444346340367/AnsiballZ_panos_op.py\", line 48, in invoke_module\n    imp.load_module('__main__', mod, module, MOD_DESC)\n  File \"/tmp/ansible_panos_op_payload_86fVYv/__main__.py\", line 159, in <module>\n  File \"/tmp/ansible_panos_op_payload_86fVYv/__main__.py\", line 130, in main\n  File \"/home/administrator/.local/lib/python2.7/site-packages/pandevice/base.py\", line 3277, in create_from_device\n    system_info = device.refresh_system_info()\n  File \"/home/administrator/.local/lib/python2.7/site-packages/pandevice/base.py\", line 3685, in refresh_system_info\n    system_info = self.show_system_info()\n  File \"/home/administrator/.local/lib/python2.7/site-packages/pandevice/base.py\", line 3642, in show_system_info\n    root = self.xapi.op(cmd=\"show system info\", cmd_xml=True)\n  File \"/home/administrator/.local/lib/python2.7/site-packages/pandevice/base.py\", line 3403, in method\n    raise the_exception\npandevice.errors.PanURLError: URLError: code: 403 reason: Forbidden\n", 
    "module_stdout": "", 
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", 
    "rc": 1

```

**Comment by shinmog** [comment]
@martino76 

403 Forbidden is incorrect authentication credentials.  Could you verify that you are using the appropriate username/password, and that username/password has access to PAN-OS?

**Comment by martino76** [comment]
I checked and credentials are correct. I can log in into this PA from the ansible box without any issue using the same credentials.

**Comment by shinmog** [comment]
@martino76 

The variable names suggest that you're using ansible credentials, not PAN-OS credentials..  Just to verify, can you try adding this to your playbook just above the and eyeball that the auth creds are as you expect them to be?

```yaml
    - debug:
        msg: 'PAN-OS host is {{ ansible_host }}, while the PAN-OS username / password is {{ ansible_user }} / {{ ansible_password }}'
```

Note that the `msg` param is double indented, not single.

**Comment by martino76** [comment]
I did and is the same. 
This is my inventory file for PA
```
[PA]
PA01 ansible_host=172.29.12.109 ansible_password=test ansible_user=test ansible_connection=local
PA02 ansible_host=172.29.12.80 ansible_password=test ansible_user=test ansible_connection=local
PA03 ansible_host=172.29.12.35 ansible_password=test ansible_user=test ansible_connection=local
```

when run my playbook I can see right credential were used

```
TASK [debug] 
ok: [PA01] => {
    "msg": "PAN-OS host is 172.29.12.109, while the PAN-OS username / password is test / test"
}
ok: [PA02] => {
    "msg": "PAN-OS host is 172.29.12.80, while the PAN-OS username / password is test / test"
}
ok: [PA03] => {
    "msg": "PAN-OS host is 172.29.12.35, while the PAN-OS username / password is test / test"
}

```

When I change dummy credential to my domain account I am getting following 

```
TASK [show system] *************************************************************************************************************************************************************************************************************************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: pandevice.errors.PanURLError: URLError: code: 403 reason: Forbidden
fatal: [PA03]: FAILED! => {"changed": false, "module_stderr": "Traceback (most recent call last):\n  File \"/home/administrator/.ansible/tmp/ansible-tmp-1553193893.32-236327256814468/AnsiballZ_panos_op.py\", line 113, in <module>\n    _ansiballz_main()\n  File \"/home/administrator/.ansible/tmp/ansible-tmp-1553193893.32-236327256814468/AnsiballZ_panos_op.py\", line 105, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/home/administrator/.ansible/tmp/ansible-tmp-1553193893.32-236327256814468/AnsiballZ_panos_op.py\", line 48, in invoke_module\n    imp.load_module('__main__', mod, module, MOD_DESC)\n  File \"/tmp/ansible_panos_op_payload_rz5G_6/__main__.py\", line 159, in <module>\n  File \"/tmp/ansible_panos_op_payload_rz5G_6/__main__.py\", line 130, in main\n  File \"/home/administrator/.local/lib/python2.7/site-packages/pandevice/base.py\", line 3277, in create_from_device\n    system_info = device.refresh_system_info()\n  File \"/home/administrator/.local/lib/python2.7/site-packages/pandevice/base.py\", line 3685, in refresh_system_info\n    system_info = self.show_system_info()\n  File \"/home/administrator/.local/lib/python2.7/site-packages/pandevice/base.py\", line 3642, in show_system_info\n    root = self.xapi.op(cmd=\"show system info\", cmd_xml=True)\n  File \"/home/administrator/.local/lib/python2.7/site-packages/pandevice/base.py\", line 3403, in method\n    raise the_exception\npandevice.errors.PanURLError: URLError: code: 403 reason: Forbidden\n", "module_stdout": "", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 1}
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: pandevice.errors.PanURLError: URLError: code: 403 reason: Forbidden
fatal: [PA01]: FAILED! => {"changed": false, "module_stderr": "Traceback (most recent call last):\n  File \"/home/administrator/.ansible/tmp/ansible-tmp-1553193893.24-109154961345515/AnsiballZ_panos_op.py\", line 113, in <module>\n    _ansiballz_main()\n  File \"/home/administrator/.ansible/tmp/ansible-tmp-1553193893.24-109154961345515/AnsiballZ_panos_op.py\", line 105, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/home/administrator/.ansible/tmp/ansible-tmp-1553193893.24-109154961345515/AnsiballZ_panos_op.py\", line 48, in invoke_module\n    imp.load_module('__main__', mod, module, MOD_DESC)\n  File \"/tmp/ansible_panos_op_payload_3IDyBX/__main__.py\", line 159, in <module>\n  File \"/tmp/ansible_panos_op_payload_3IDyBX/__main__.py\", line 130, in main\n  File \"/home/administrator/.local/lib/python2.7/site-packages/pandevice/base.py\", line 3277, in create_from_device\n    system_info = device.refresh_system_info()\n  File \"/home/administrator/.local/lib/python2.7/site-packages/pandevice/base.py\", line 3685, in refresh_system_info\n    system_info = self.show_system_info()\n  File \"/home/administrator/.local/lib/python2.7/site-packages/pandevice/base.py\", line 3642, in show_system_info\n    root = self.xapi.op(cmd=\"show system info\", cmd_xml=True)\n  File \"/home/administrator/.local/lib/python2.7/site-packages/pandevice/base.py\", line 3403, in method\n    raise the_exception\npandevice.errors.PanURLError: URLError: code: 403 reason: Forbidden\n", "module_stdout": "", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 1}
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: pandevice.errors.PanURLError: URLError: code: 403 reason: Forbidden
fatal: [PA02]: FAILED! => {"changed": false, "module_stderr": "Traceback (most recent call last):\n  File \"/home/administrator/.ansible/tmp/ansible-tmp-1553193893.28-223629792998174/AnsiballZ_panos_op.py\", line 113, in <module>\n    _ansiballz_main()\n  File \"/home/administrator/.ansible/tmp/ansible-tmp-1553193893.28-223629792998174/AnsiballZ_panos_op.py\", line 105, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/home/administrator/.ansible/tmp/ansible-tmp-1553193893.28-223629792998174/AnsiballZ_panos_op.py\", line 48, in invoke_module\n    imp.load_module('__main__', mod, module, MOD_DESC)\n  File \"/tmp/ansible_panos_op_payload_bgjir2/__main__.py\", line 159, in <module>\n  File \"/tmp/ansible_panos_op_payload_bgjir2/__main__.py\", line 130, in main\n  File \"/home/administrator/.local/lib/python2.7/site-packages/pandevice/base.py\", line 3277, in create_from_device\n    system_info = device.refresh_system_info()\n  File \"/home/administrator/.local/lib/python2.7/site-packages/pandevice/base.py\", line 3685, in refresh_system_info\n    system_info = self.show_system_info()\n  File \"/home/administrator/.local/lib/python2.7/site-packages/pandevice/base.py\", line 3642, in show_system_info\n    root = self.xapi.op(cmd=\"show system info\", cmd_xml=True)\n  File \"/home/administrator/.local/lib/python2.7/site-packages/pandevice/base.py\", line 3403, in method\n    raise the_exception\npandevice.errors.PanURLError: URLError: code: 403 reason: Forbidden\n", "module_stdout": "", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 1}
        to retry, use: --limit @/home/administrator/ansible/network-engine/pa_show.retry

```

**Comment by martino76** [comment]
Does anyone is able to test it against version lower then 8.1.8?

**Comment by martino76** [comment]
Issue has been solved it was related to lack of admin role which was missing xml_api functionality on some of the PA firewall.s

**Comment by shinmog** [comment]
@martino76 

Ah.  I thought the 403 was specifically "incorrect username/password," didn't realize it could be permissions based as well.  Thanks for reporting this, and I'm glad you found it.

Closing as this seems to be resolved.
