### ISSUE TITLE
botocore Unable to locate credentials

### ISSUE THREAD

**Issue by Zjemm** [PaloAltoNetworks/ansible-pan#45]
Hi there

i'm trying the ansible playbook aws/provision_fw_w_srule.yml

at first i missed that i should set "aws configure"  and fill in my account. now that that is done, from within python i can list my s3 buckets, so the account is working.

now when i run the playbook i get the following output error:

The full traceback is:
Traceback (most recent call last):
  File "/tmp/ansible_lAMqTZ/ansible_module_cloudformation.py", line 604, in <module>
    main()
  File "/tmp/ansible_lAMqTZ/ansible_module_cloudformation.py", line 540, in main
    stack_info = get_stack_facts(cfn, stack_params['StackName'])
  File "/tmp/ansible_lAMqTZ/ansible_module_cloudformation.py", line 443, in get_stack_facts
    stack_response = cfn.describe_stacks(StackName=stack_name)
  File "/tmp/ansible_lAMqTZ/ansible_modlib.zip/ansible/module_utils/cloud.py", line 153, in retry_func
botocore.exceptions.NoCredentialsError: Unable to locate credentials

fatal: [localhost]: FAILED! => {
    "changed": false, 
    "module_stderr": "Traceback (most recent call last):\n  File \"/tmp/ansible_lAMqTZ/ansible_module_cloudformation.py\", line 604, in <module>\n    main()\n  File \"/tmp/ansible_lAMqTZ/ansible_module_cloudformation.py\", line 540, in main\n    stack_info = get_stack_facts(cfn, stack_params['StackName'])\n  File \"/tmp/ansible_lAMqTZ/ansible_module_cloudformation.py\", line 443, in get_stack_facts\n    stack_response = cfn.describe_stacks(StackName=stack_name)\n  File \"/tmp/ansible_lAMqTZ/ansible_modlib.zip/ansible/module_utils/cloud.py\", line 153, in retry_func\nbotocore.exceptions.NoCredentialsError: Unable to locate credentials\n", 
    "module_stdout": "", 
    "msg": "MODULE FAILURE", 
    "rc": 0
}

it seems not able to find my credentials, but how to solve this? (Unable to locate credentials)
when running aws configure list, my account just shows up

any idea?

**Comment by Zjemm** [comment]
hmmm found it :)

didnt need to run it as sudo, apparently it also takes other aws settings then.
